### ISSUE TITLE
Upgrade Monolog dependency to support v3.3+

### ISSUE THREAD

**Issue by pveiga2** [Adyen/php-webhook-module#52]
**Is your feature request related to a problem? Please describe.**
The "adyen/php-webhook-module" is the only library in our project which does not support Monolog v3. 
Since some other libraries now require Monolog v3.3+, we had to make a "local" copy of this library just to change its dependencies, or else we were stuck.
The "adyen/php-api-library" had this same issue, but has finally upgraded their dependencies last week.

**Describe the solution you'd like**
The simplest fix would be to allow Monolog v3.3 in your composer.json:
 "monolog/monolog": "^1.16 || ^2.0 || ^3.3"

**Describe alternatives you've considered**
Our current alternative is to keep a "local" copy of this library, changed its composer.json and then "cheat" composer using the local repositories feature:
`  "repositories":      [
    {
      "type":    "path",
      "url":     "./libraries/adyen/php-webhook-module",
      "options": {
        "symlink":  true,
        "versions": {
          "adyen/php-webhook-module": "0.6.0"
        }
      }
    }
  ],`

**Comment by pveiga2** [comment]
If I get enough time, I would like to help by creating a pull-request for this... 
But i believe this should be only about changing 1 line in composer.json

**Comment by candemiralp** [comment]
Hello @pveiga2,

Thank you for raising this issue and and the pull-request as a solution. We will merge this pull request as soon as possible.

Best Regards,
Can
